@host = http://localhost:5139
@cultureCode = en-US

### 
GET {{host}}/api/products?cultureCode={{cultureCode}}

### 
GET {{host}}/api/shopping-carts/580d1e60-8916-44d8-bb92-5e2426e93306?cultureCode={{cultureCode}}
