@host = http://localhost:5139
@cultureCode = en-US

###
### Get all
###

GET {{host}}/api/products?cultureCode={{cultureCode}}

###
### Get shopping cart
###

GET {{host}}/api/shopping-carts/580d1e60-8916-44d8-bb92-5e2426e93306?cultureCode={{cultureCode}}

###
### PUT
###

### Get product #1 initial state
GET {{host}}/api/v2/products/1

### PUT works right away!
PUT {{host}}/api/v2/products/1
Content-Type: application/json

{
  "category": "Toy",
  "translations": {
    "en-US": {
      "name": "SpongeBob SquarePants plush",
      "description": ""
    },
    "fr-FR": {
      "name": "Peluche Bob l'éponge",
      "description": ""
    }
  }
}

